### PR TITLE
Add unique styling to dependencies subsection

### LINKED ISSUE #22: Style dependencies subsection
Add new styling to dependencies subsection to differentiate it from the rest.

For example:

> screen shot 2016-03-14 at 12 55 26 pm

### PR DESCRIPTION
**Pull request by jsbean**
This pull request adds updated styling for the dependencies subsection.

screen shot 2016-03-14 at 1 32 17 pm

Closes #22.

### CODE REVIEW

**Comment by jsbean** [comment]
@delucis, as I am completely uninitiated with the worlds of CSS, let me know if this is super bad practice.

That is, is there a way to "subclass" CSS classes?

**Comment by delucis** [comment]
I would refactor as follows:
1. Revert all changes to `InjectDependencies.rb`
2. Use the existing `#dependencies` id to target the subsections:

``` scss
// Dependencies
#dependencies {
  .nav-group-name {
    border-bottom: 1px solid $navigation_border_color;
    padding: $gutter/2 0 $gutter/2 $gutter;
    background-color: coral;
  }
  .nav-group-name-link {
    font-weight: 800;
    color: white;
  }
  .nav-group-task-link {
    color: white;
    opacity: 0.75;
  }
}
```

The nesting here works because the `*.scss` file is being processed in Jazzy to output pure CSS. Each nesting renders out, e.g. `#dependencies .nav-group-name`.

For extra future flexibility you could declare your colours as variables at the head of `jazzy.css.scss`, e.g.

``` scss
$dependencies_bg_color = coral;
$dependencies_link_color = white;
```

And use variables in your `#dependencies` declaration, e.g.

``` scss
  .nav-group-task-link {
    color: $dependencies_link_color;
    opacity: 0.75;
  }
```

##### For extra elegance points :moneybag: :moneybag: :moneybag:

[Learn about mixins](http://sass-lang.com/guide#topic-6) and create a mixin that styles a named subsection when passed colour (and other) parameters.

Once you have a functioning mixin, you could then style subsections to your heart’s content:

``` scss
#dependencies { @include menu-subsections( parameters… ); }
#custom-category-1 { @include menu-subsections( parameters… ); }
#custom-category-2 { @include menu-subsections( parameters… ); }
```

**Comment by jsbean** [comment]
:+1: :heart:

**Comment by jsbean** [comment]
@delucis, for the current class (`.nav-group-name`), I needed a **`&`**, i.e.,

``` SASS
#dependencies {
    &.nav-group-name {
    border-bottom: 1px solid $navigation_border_color;
    padding: $gutter/2 0 $gutter/2 $gutter;
    background-color: coral;
...
```

Is that legit, or did I screw something else up?

**Comment by jsbean** [comment]
Ew, not sure what a `refector` is (4f86c14), but I did it, and I am sorry.

**Comment by delucis** [comment]
Oh right, sorry, I wasn’t paying attention. Yes the `&` makes sense because that renders to `#dependencies.nav-group-name` (i.e. a node with both that id and that class), rather than `#dependencies .nav-group-name` (a node with that class, inside a node with that id).

Given this though, you could actually also do:

``` scss
// Dependencies
#dependencies {
  border-bottom: 1px solid $navigation_border_color;
  padding: $gutter/2 0 $gutter/2 $gutter;
  background-color: coral;
  .nav-group-name-link {
    font-weight: 800;
    color: white;
  }
  .nav-group-task-link {
    color: white;
    opacity: 0.75;
  }
}
```

**Comment by jsbean** [comment]
I'll get to the mixins in due time.

Is this acceptable as it stands?

**Comment by delucis** [comment]
If it works, all is well.

:+1:

**Comment by jsbean** [comment]
Ok. :bomb: :dollar:

**Pull request merged**
