### PR TITLE
Refactor file structure

### LINKED ISSUE #30: Refactor to tidy root
The root is looking rather cluttered with among others
- **Shell:** `GenerateDocumentation.sh`, `GenerateFrontpage.sh`, `HandleDependencies.sh`
- **Ruby:** `InjectDependencies.rb`, `Md2Mo.rb`
- **Mustache:** `index.mo`, `main.mo`

I would suggest some refactoring to clean out the root moving things to `dependencies` or `build` for generated files.
##### Root could keep
- A master shell script: `build.sh`
- `index.html`
- `README.md`
- `LICENSE`
- `Gemfile` & `Gemfile.lock`
- _perhaps_ also `main.md` although that could equally go in `dependencies`
##### Redistribution
- shell scripts, ruby scripts, and `dependencies/mo` all move to `dependencies/scripts`
- mustache templates move to `dependencies/templates`
- if `main.md` gets moved, move to `dependencies/src`
- consider moving `dependencies/bean` to `dependencies/templates/bean`

Obviously this would all require rewriting of scripts to handle new path structures.

### PR DESCRIPTION
**Pull request by jsbean**
This pull request refactors the file structure of this repo.
- `Bash`, and `ruby` scripts moved to `dependencies/scripts`
- `mustache` templates and `bean` moved to `dependencies/templates`

References to these files in various scripts have been updated.

Closes #30.

### CODE REVIEW

**Comment by jsbean** [comment]
@delucis, wanna give this a look :8ball: ?

**Comment by delucis** [comment]
Is `GenerateDocumentation.sh` still running?

Could we move most of it to `dependencies/scripts` and leave a minimal `build.sh` in root?

``` sh
#!/bin/bash

# Generate documentation
./dependencies/scripts/GenerateDocumentation.sh

# Generate main index
./dependencies/scripts/GenerateFrontpage.sh
```

**Comment by delucis** [comment]
I guess the easiest test would be to delete all framework subdirectories in `site` and the `hashstash` before trying to rebuild.

**Comment by jsbean** [comment]
Totally. I wanted to get that out of there, but I still wanted a hook to grab. Will do this.

**Comment by delucis** [comment]
Nice.

I missed `hashstash` in my original audit. That might best be moved to `build/hashstash`?

**Comment by jsbean** [comment]
Will do.

**Comment by jsbean** [comment]
@delucis, a few questions:
- Is `main.mo` generated anew every time? If so, where is that generated, and how can we get it out of root?
- I tried to relocate `hashstash` in `GenerateDocumentation.sh`, but it was unwilling to cooperate. I tried to move it to `build` -- but does `build` get destroyed then rebuilt? Maybe I need to cache the stash?

**Comment by delucis** [comment]
### `main.mo`

`main.mo` is regenerated from `main.md` each time `Md2Mo.rb` is called in `GenerateFrontpage.sh`.

`Md2Mo.rb` takes two optional arguments:
1. a read path
2. a write path

If no second argument (i.e. write path) is provided, it assumes you want to output your `*.mo` to the same place you read from, e.g. if reading from `../../foo.md`, will write to `../../foo.mo`.

Right now it’s [reading `main.md` from the root and outputting alongside that](https://github.com/dn-m/dn-m.github.io/blob/tidyroot/dependencies/scripts/GenerateFrontpage.sh#L47). Adding `dependencies/templates/main.mo` to that line ought to work I imagine?

Then there’s just a question mark over what exactly the scope is while `index.mo` is being processed, and whether or not it sees the `{{> main.mo}}` partial if we move it. If it _doesn’t_ see `main.mo`, I believe you can declare the partial with a path, e.g. `{{> dependencies/templates/main.mo}}`. It’s probably also worth deleting all existing `main.mo` copies before testing to ensure `index.mo` is not finding one generated in the past.

I know that it’s a bit weird to be generating a “template” each time, but think of `main.mo` as just an HTML fragment that the _actual_ template — `index.mo` — can use.

### `hashstash`

You’re right, we can’t safely put things into `build` because it gets cleaned when we copy in CSS, JS & image assets. I guess it could be left in root. Or put in `dependencies` but somehow that doesn’t seem quite right. It’s also less crucial because `hashstash` is ignored by git, so its not cluttering up the versioned repo.

### While we’re here

For cleanliness, I’d move the block starting `# Clean and build assets for main index` at the end of `GenerateDocumentation.sh` to the beginning of `GenerateFrontpage.sh`.

I would also not chain those two scripts there, but call them each individually from `build.sh`. It’s a small change, but it separates out the main Jazzy docs side of things from the frontpage side of things, which could be useful if you ever wanted to do only one or the other (e.g. you update `main.md`, and just want to regenerate the main page without running the whole shebang).

**Comment by jsbean** [comment]
@delucis, lemme know if I am missing anything here :eyes:.

**Comment by delucis** [comment]
Looking good to me! :+1: :+1: :+1:

**Pull request merged**
